version: "3"

services:
  redis:
    image: redis:7-alpine
#    command:
#      - 'redis-server'
#      - '--loglevel ${REDIS_LOGLEVEL:-warning}'
#      - '--databases 1'
#      - '--save 5 1'
#      - '--maxmemory ${REDIS_MAXMEM:-3gb}'
#      - '--maxmemory-policy ${REDIS_POLICY:-noeviction}'
#      - '--requirepass ${REDIS_PASS}'
    volumes:
      - ./redis_data:/data
      - ./redis-stack.conf:/redis-stack.conf
    ports:
      - "6379:6379"
